#!/bin/sh

echo ==entry==


echo "argv"
echo $#
echo $@
echo start jupyter ...

echo $@ > ~/argv11111.txt

shift 2
echo -----------------------------------
echo $@ 

echo "jupyter notebook $@"
bash -c "jupyter notebook $@"


